[package]
name = "prisma-cli"
version = "0.0.0"
description = "Your Prisma Cli"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8", features = ["migrations"]}
